import { Metadata } from "next";
import "@/app/styles/globals.css";
import "@/app/styles/styles.css";
import { poppins, inter } from "../styles/font";
import { Footer, MiniNav, Navbar } from "../components/layouts";
import NextTopLoader from "nextjs-toploader";
import { colors } from "../styles/colors";

import StoreProvider from "../StoreProvider";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable}`}>
        <StoreProvider>
          <NextTopLoader color={colors.loader} />
          <MiniNav />
          <Navbar />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
