import { Metadata } from "next";
import "@/app/styles/globals.css";
import "@/app/styles/styles.css";
import { poppins, inter } from "../../styles/font";
import { AccountHeader, AccountSidebar } from "@/app/components/Account";
import { BreadCrumb } from "@/app/components/common";
import { accountBreadCrums } from "@/app/utils/data";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className={`${poppins.variable} ${inter.variable}`}>
        <AccountHeader />
        <div className="resContainer md:flex">
          <div className="w-full md:w-[30%] lg:[25%]">
            <AccountSidebar />
          </div>
          <div className="w-full md:w-[70%] lg:[75%]"> {children}</div>
        </div>
      </main>
    </>
  );
}
